Description: >
  Nick Askam / Udacity
  This template deploys a VPC. Testing update
Resources:
  UdacityVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true